branches:
  main:
    tag: beta
    increment: Patch
    mode: ContinuousDeployment
  develop:
    tag: alpha
    increment: Patch
    mode: ContinuousDeployment
  feature:
    tag: useBranchName
    increment: Patch
    mode: ContinuousDeployment
